### ISSUE TITLE
where is the data importance sampling in the code？

### ISSUE THREAD

**Issue by mxjecho** [ShunLu91/PA-DA#1]
Hi, I am interested in your work.

Could you please share the data importance sampling code with me?

**Comment by ShunLu91** [comment]
Thanks for your interest. Please refer to the `nasbench201/train_panda_201.py` and the data importance sampling code is in this [fragment](https://github.com/ShunLu91/PA-DA/blob/e65ad6235ebc6cd76da181d83b4dfcae6622d216/nasbench201/train_panda_201.py#L169).

**Comment by ShunLu91** [comment]
As there have been no further updates in these months, I will now close this issue. If you have any other questions, please feel free to re-open it and we will be happy to assist you.
